name: inspire
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - python=3.8.15
  - pytorch=1.12.1
  - scanpy=1.8.2
  - anndata=0.9.2
  - pandas=1.5.3
  - numpy=1.24.4
  - louvain=0.8.0
  - umap-learn=0.5.5
  - numba=0.58.1
  - matplotlib=3.5.3
  - python-annoy=1.17.2
  - scikit-misc=0.1.4